edsys_assesment/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import registration.urls
import transfer_certificate.urls
import strike_off.urls
import id_generation.urls
import medical.urls
import attendance.urls
import password_reset.urls
import masters.urls
import promotions.urls
import assessment.urls
import parent_portal.urls
import rest_api.urls
from registration import views
import os
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    url(r'^api/', include(rest_api.urls, namespace='api')),
    url(r'^school/', include(registration.urls, namespace='registration')),
    url(r'^$', views.Login, name='login'),
    url(r'^school/', include(transfer_certificate.urls, namespace='transfer_certificate')),
    url(r'^school/', include(strike_off.urls, namespace='strike_off')),
    url(r'^school/', include(id_generation.urls, namespace='id_generation')),
    url(r'^school/', include(medical.urls, namespace='medical')),
    url(r'^school/', include(password_reset.urls, namespace='password_reset')),
    url(r'^school/', include(attendance.urls, namespace='attendance')),
    url(r'^school/', include(masters.urls, namespace='masters')),
    url(r'^school/', include(promotions.urls, namespace='promotions')),
    url(r'^school/', include(assessment.urls, namespace='assessment')),
    url(r'^school/', include(parent_portal.urls, namespace='parent_portal')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('social_django.urls', namespace='social')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^sso/', include("djssoserver.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ADMIN_URL_ENABLE:
    urlpatterns.append(url(r'^admin/', admin.site.urls))

id_generation/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static, serve


app_name = 'id_generation'

urlpatterns = [
                  url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
                  url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),


    ######################################### ID Details ###################################

                  url(r'^id_menu/$', views.IdMenu, name='id_menu'),
                  url(r'^id_generator/$', views.IdGenerator, name='id_generator'),
                  url(r'^updated_student_template/$', views.UpdatedStudentTemplate, name='updated_student_template'),
                  url(r'^view_student_template/$', views.ViewStudentTemplate, name='view_student_template'),
                  url(r'^view_student_ID_list/$', views.IdGeneratorList, name='view_student_ID_list'),
                  url(r'^id_generate/(?P<std_id>[0-9]+)$', views.IdGenerate, name='id_generate'),
                  url(r'^student_template/$', views.StudentTemplate, name='student_template'),
                  url(r'^student_template_select/$', views.StudentTemplateSelect, name='student_template_select'),
                  url(r'^multiple_student_ID_list/$', views.MultipleStudentIDlist, name='multiple_student_ID_list'),
                  url(r'^print_back/$', views.PrintBack, name='print_back'),
                  url(r'^print_id/(?P<std_id>[0-9]+)$', views.PrintID, name='print_id'),

                  # url(r'^multiple_student_ID_list/$',views.MultipleStudentIDlist, name='multiple_student_ID_list'),
                  url(r'^multiple_ststaff_ID_print/$', views.MultipleStaffIDCard, name='multiple_ststaff_ID_print'),
                  # url(r'^student_template/$',views.StudentTemplate, name='student_template'),

                  url(r'^view_staff_list/$', views.ViewStaffList, name='view_staff_list'),
                  url(r'^staff_template/$', views.StaffTemplate, name='staff_template'),
                  url(r'^staff_id_generate/(?P<usr_id>[0-9]+)$', views.StaffIdGenerate, name='staff_id_generate'),
                  url(r'^print_staff_id/(?P<usr_id>[0-9]+)$', views.PrintStaffID, name='print_staff_id'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masters/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static

app_name = 'masters'

urlpatterns = [

                  ########=================================odoo configuration======================================================
                  url(r'^template_odoo_config_list/$', views.TemplateOdooConfigList, name='template_odoo_config_list'),
                  url(r'^add_odoo_config/$', views.AddOdooConfig, name='add_odoo_config'),
                  url(r'^template_update_config/(?P<config_id>[0-9]+)$', views.TemplateUpdateOdooConfig,
                      name='template_update_config'),
                  url(r'^update_odoo_config/$', views.UpdateOdooConfig, name='update_odoo_config'),
                  url(r'^test_connection/$', views.TestOdooConnection, name='test_connection'),
                  url(r'^start_syncing/$', views.StartOdooSync, name='start_syncing'),
                  url(r'^sync_switch/$', views.OdooSyncOnOff, name='sync_switch'),
                  #=================================================================================================================

                  url(r'^month_masters/$', views.MonthMasters, name='month_masters'),

                  url(r'^masters_home/$', views.ManageMasters, name='masters_home'),
                  url(r'^data_access/$', views.DataAccessMasters, name='data_access'),
                  url(r'^religion_masters/$', views.ManageReligionMasters, name='religion_masters'),
                  url(r'^add_religion_masters/$', views.AddReligionMasters, name='add_religion_masters'),
                  url(r'^update_religion/(?P<religion_id>[0-9]+)$', views.UpdateReligion, name='update_religion'),
                  url(r'^save_updated_religion/$', views.SaveUpdatedReligion, name='save_updated_religion'),
                  url(r'^delete_religion/(?P<religion_id>[0-9]+)$', views.DeleteReligion, name='delete_religion'),

                  # =-==-=-=-=-==-=-=-Nationality Urls=-=-=-====-=-=-=-=

                  url(r'^nationality_masters/$', views.ManageNationalityMasters, name='nationality_masters'),
                  url(r'^add_nationality_masters/$', views.AddNationalityMasters, name='add_nationality_masters'),
                  url(r'^update_nationality/(?P<nationality_id>[0-9]+)$', views.UpdateNationality,
                      name='update_nationality'),
                  url(r'^save_updated_nationality/$', views.SaveUpdatedNationality, name='save_updated_nationality'),
                  url(r'^delete_nationality/(?P<nationality_id>[0-9]+)$', views.DeleteNationality,
                      name='delete_nationality'),

                  # =-=-=-=-=-=-=-=-=-=--Department Master Urls=-=-=-=-=-=-=-=-=-=-
                  url(r'^department_master/$', views.ManageDepartment, name='department_master'),
                  url(r'^add_department_masters/$', views.AddDepartmentMasters, name='add_department_masters'),
                  url(r'^update_department/(?P<department_id>[0-9]+)$', views.UpdateDepartment,
                      name='update_department'),
                  url(r'^save_updated_department/$', views.SaveUpdatedDepartment, name='save_updated_department'),
                  url(r'^delete_department/(?P<department_id>[0-9]+)$', views.DeleteDepartment,
                      name='delete_department'),

                  # =-==-=-=-=-==-=-=-Exam Urls=-=-=-====-=-=-=-=

                  url(r'^exam_masters/$', views.ManageExamMasters, name='exam_masters'),
                  url(r'^add_exam_masters/$', views.AddExamMasters, name='add_exam_masters'),
                  url(r'^update_exam/(?P<exam_type_id>[0-9]+)$', views.UpdateExam,
                      name='update_exam'),
                  url(r'^save_updated_exam/$', views.SaveUpdatedExam, name='save_updated_exam'),
                  url(r'^delete_exam/(?P<exam_type_id>[0-9]+)$', views.DeleteExam,
                      name='delete_exam'),

                  # =-==-=-=-=-==-=-=-Rubrics Urls=-=-=-====-=-=-=-=

                  url(r'^rubrics_masters/$', views.RubricsMasters, name='rubrics_masters'),
                  url(r'^add_rubrics_masters/$', views.AddRubricsMasters, name='add_rubrics_masters'),
                  url(r'^update_rubrics/(?P<rubrics_id>[0-9]+)$', views.UpdateRubrics,
                      name='update_rubrics'),
                  url(r'^save_updated_rubrics/$', views.SaveUpdatedRubrics, name='save_updated_rubrics'),
                  url(r'^delete_rubrics/(?P<rubrics_id>[0-9]+)$', views.DeleteRubrics,
                      name='delete_rubrics'),

                  url(r'^rubrics_category/$', views.RubricsCategory, name='rubrics_category'),
                  url(r'^add_rubrics_category/$', views.AddRubricsCategory, name='add_rubrics_category'),
                  url(r'^update_rubrics_catgory/(?P<rubrics_category_id>[0-9]+)$', views.UpdateRubricsCategory,
                      name='update_rubrics_catgory'),
                  url(r'^save_updated_rubrics_category/$', views.SaveUpdatedRubricsCategory,
                      name='save_updated_rubrics_category'),
                  url(r'^delete_rubrics_category/(?P<rubrics_category_id>[0-9]+)$', views.DeleteRubricsCategory,
                      name='delete_rubrics_category'),

                  url(r'^nationality_group/$', views.NationalityGroup, name='nationality_group'),
                  url(r'^add_nationality_group/$', views.AddNationalityGroup, name='add_nationality_group'),

                  url(r'^update_nationality_group/(?P<nationality_group_id>[0-9]+)$', views.UpdateNationalityGroup,
                      name='update_nationality_group'),
                  url(r'^save_updated_nationality_group/$', views.SaveUpdatedNationalityGroup,
                      name='save_updated_nationality_group'),

                  url(r'^delete_nationality_group/(?P<nationality_group_id>[0-9]+)$', views.DeleteNationalityGroup,
                      name='delete_nationality_group'),

                  # =-==-=-=-=-==-=-=-Home Urls=-=-=-====-=-=-=-=
                  url(r'^house_master_list/$', views.HouseMasterList, name='house_master_list'),
                  url(r'^add_house/$', views.AddHouse, name='add_house'),
                  url(r'^update_hose/(?P<house_id>[0-9]+)$', views.UpdateHose,
                      name='update_hose'),
                  url(r'^save_updated_house/$', views.SaveUpdatedHouse, name='save_updated_house'),
                  url(r'^delete_house/(?P<house_id>[0-9]+)$', views.DeleteHouse,
                      name='delete_house'),

                  url(r'^nationality_group_mapping/$', views.NationalityGroupMapping, name='nationality_group_mapping'),

                  url(r'^group_nationality_mapping/$', views.GroupNationalityMapping, name='group_nationality_mapping'),
                  url(r'^save_group_nationality_mapping/$', views.SaveGroupNationalityMapping,
                      name='save_group_nationality_mapping'),
                  url(r'^delete_group_nationality_mapping/$', views.DeleteGroupNationalityMapping,
                      name='delete_group_nationality_mapping'),

                  url(r'^tc_type_master/$', views.TCTYPEMASTER, name='tc_type_master'),

                  # =-==-=-=-=-==-=-=-Assessment Configration Urls=-=-=-====-=-=-=-=

                  url(r'^assessment_configration/$', views.AssessmentConfigration, name='assessment_configration'),
                  url(r'^add_assessment_configration/$', views.AddAssessmentConfigration,
                      name='add_assessment_configration'),
                  url(r'^update_assessment_configration/(?P<ass_config_id>[0-9]+)$', views.UpdateAssessmentConfigration,
                      name='update_assessment_configration'),

                  url(r'^save_updated_assessment_configraton/$', views.SaveUpdatedAssessmentConfigraton,
                      name='save_updated_assessment_configraton'),
                  url(r'^delete_assessment_configration/(?P<ass_config_id>[0-9]+)$', views.DeleteAssessmentConfigration,
                      name='delete_assessment_configration'),

                  url(r'^assessment_configrtion_roundoff/$', views.AssessmentConfigrtionRoundOff,
                      name='assessment_configrtion_roundoff'),

                  url(r'^assessment_round_off/$', views.AssessmentRoundOff, name='assessment_round_off'),
                  url(r'^add_round_off/$', views.AddRoundOff, name='add_round_off'),
                  # url(r'^round_off_list/$', views.RoundOffList, name='round_off_list'),
                  url(r'^update_round_off/', views.UpdateRoundOff,
                      name='update_round_off'),
                  url(r'^save_updated_round_off/$', views.SaveUpdatedRoundOff, name='save_updated_round_off'),
                  url(r'^delete_round_off/(?P<round_off_id>[0-9]+)$', views.DeleteRoundOff,
                      name='delete_round_off'),
                  url(r'^active_round/$', views.ActiveRound, name='active_round'),
                  url(r'^inactive_round/$', views.InActiveRound, name='inactive_round'),

                  # ============== Section Type ============================

                  url(r'^section_type_master/$', views.SectionTypeMaster, name='section_type_master'),
                  url(r'^add_section_type/$', views.AddSectionType, name='add_section_type'),
                  url(r'^save_section_type/$', views.SaveSectionType, name='save_section_type'),
                  url(r'^update_section_type/(?P<type_id>[0-9]+)$', views.UpdateSectionType,name='update_section_type'),
                  url(r'^save_updated_section_type/$', views.SaveUpdateSectionType, name='save_updated_section_type'),
                  url(r'^delete_section_type/(?P<type_id>[0-9]+)$', views.DeleteSectionType, name='delete_section_type'),

parent_portal/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static, serve


app_name = 'parent_portal'


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    ######################################### ID Details ###################################
    url(r'^parent_portal_home/$',views.ParentPortalMenu, name='parent_portal_home'),
    url(r'^parents_students_menu/$',views.ParentsStudentsMenu, name='parents_students_menu'),
    url(r'^student_list/$',views.StudentList, name='student_list'),
    url(r'^parent_notification_log/$',views.ParentNotificationLog, name='parent_notification_log'),
    url(r'^view_student_detalis/(?P<std_id>[0-9]+)$', views.ViewStudentDetalis, name='view_student_detalis'),
    url(r'^child_details_updated_request/$',views.ChildUpdateRequest, name='child_details_updated_request'),
    url(r'^view_student_updatation_details/(?P<std_id>[0-9]+)$', views.UpdatedStudentDetails, name='view_student_updatation_details'),

    # url(r'^view_update_parent/(?P<parent_id>[0-9]+)$', views.ViewUpdateParent, name='view_update_parent'),
    url(r'^view_update_parent/$',views.ViewUpdateParent, name='view_update_parent'),
    url(r'^save_updated_parent_portal/$',views.SaveUpdatedParentPortal, name='save_updated_parent_portal'),

    url(r'^view_parent_updatation_details/(?P<std_id>[0-9]+)$', views.UpdatedParentDetails, name='view_parent_updatation_details'),
    # url(r'^view_student_ID_list/$',views.IdGeneratorList, name='view_student_ID_list'),
    # url(r'^id_generate/(?P<std_id>[0-9]+)$', views.IdGenerate, name='id_generate'),
    # url(r'^print_id/(?P<std_id>[0-9]+)$',views.PrintID, name='print_id'),
    # url(r'^multiple_student_ID_list/$',views.MultipleStudentIDlist, name='multiple_student_ID_list'),
    # url(r'^multiple_ststaff_ID_print/$',views.MultipleStaffIDCard, name='multiple_ststaff_ID_print'),
    # url(r'^student_template/$',views.StudentTemplate, name='student_template'),
    #
    # url(r'^view_staff_list/$',views.ViewStaffList, name='view_staff_list'),
    # url(r'^staff_template/$',views.StaffTemplate, name='staff_template'),
    # url(r'^staff_id_generate/(?P<usr_id>[0-9]+)$',views.StaffIdGenerate, name='staff_id_generate'),
    # url(r'^print_staff_id/(?P<usr_id>[0-9]+)$', views.PrintStaffID, name='print_staff_id'),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parent_portal/templates/parent_portal_menu.html
{% extends "parent_portal_base.html" %}
{% load staticfiles %}



{% block styleBlock %}
    <sctipt>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </sctipt>

    <style type="text/css">
        .page-bar {
            margin-bottom: 1px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="page-bar" style="margin-bottom: 1px;">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{% url 'registration:home' %}">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>

            <li>
                <span>Parent Portal</span>
            </li>
        </ul>
    </div>


    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert" style="color: black;">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        </div>
    {% endfor %}

    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light ">
        <div class="portlet-body">
            <div class="tiles">
                <div class="tile bg-green-turquoise" style="height: 170px !important;width: 50% !important;">
                    <a href="{% url 'parent_portal:parents_students_menu' %}">
                        <div class="tile-body">
                                <i class="fa fa-id-card" aria-hidden="true"></i>
                        </div>
                        <div class="tile-object">
                            <div class="name text-success"><h4>Parent & Students Profiles </h4></div>
                        </div>
                    </a>
                </div>

                {% if 'transfer_certificate.can_view_transfer_certificate' in perms %}
                    <div class="tile double selected bg-blue" style="height: 150px !important;width: 410px !important;">
                        <a href="{% url 'transfer_certificate:tc_detail' %}" class="nav-link nav-toggle">
                            <div class="tile-body">
                                <i class="fa glyphicon glyphicon-education"></i>
                            </div>
                            <div class="tile-object">
                                <div class="name">
                                    <h4>Transfer Certificate</h4>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endif %}


{#                {% if 'registration.can_view_report_card' in perms %}#}
{#                    <div class="tile" style="height: 150px !important;width: 415px !important;">#}
{#                        <a href="{{ jwt }}">#}
{#                            <div class="tile-body" style="background-color: #1f2b3d">#}
{#                                <i class="icon-book-open"></i>#}
{#                            </div>#}
{#                            <div class="tile-object">#}
{#                                <div class="name">#}
{#                                    <h4>Report Card</h4>#}
{#                                </div>#}
{#                            </div>#}
{#                        </a>#}
{#                    </div>#}
{#                {% endif %}#}

{#                <div class="tile bg-blue" style="height: 170px !important;width: 48% !important;">#}
{#                    <a href="{% url 'id_generation:student_template' %}">#}
{##}
{#                        <div class="tile-body">#}
{#                                <i class="fa fa-id-card" aria-hidden="true"></i>#}
{#                        </div>#}
{#                        <div class="tile-object">#}
{#                            <div class="name "><h4  >Student ID Card - Template</h4></div>#}
{##}
{#                        </div>#}
{#                    </a>#}
{#                </div>#}

{#                <div class="tile double-down bg-purple-studio" style="height: 170px !important;width: 48% !important;">#}
{#                    <a href="{% url 'id_generation:view_staff_list' %}">#}
{##}
{#                        <div class="tile-body">#}
{#                            <i class="fa fa-id-badge " aria-hidden="true"></i>#}
{##}
{#                        </div>#}
{#                        <div class="tile-object">#}
{#                            <div class="name "><h4  >Staff ID Cards</h4></div>#}
{##}
{#                        </div>#}
{#                    </a>#}
{#                </div>#}
{##}
{#                <div class="tile bg-blue-hoki" style="height: 170px !important;width: 48% !important;">#}
{#                    <a href="{% url 'id_generation:staff_template' %}">#}
{##}
{#                        <div class="tile-body">#}
{#                            <i class="fa fa-id-badge " aria-hidden="true"></i>#}
{##}
{#                        </div>#}
{#                        <div class="tile-object">#}
{#                            <div class="name "><h4  >Staff ID Card - Template</h4></div>#}
{##}
{#                        </div>#}
{#                    </a>#}
{#                </div>#}

            </div>
        </div>
    </div>
{% endblock %}

parent_portal/templates/parent_students_menu.html
{% extends "parent_portal_base.html" %}
{% load staticfiles %}



{% block styleBlock %}
    <sctipt>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </sctipt>

    <style type="text/css">
        .page-bar {
            margin-bottom: 1px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="page-bar" style="margin-bottom: 1px;">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{% url 'registration:home' %}">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>

             <li>

                <a href="{% url 'parent_portal:parent_portal_home' %}"> Parent Portal</a>
                <i class="fa fa-angle-right"></i>
            </li>

            <li>
                <span>Parent & Student Menu</span>
            </li>
        </ul>
    </div>


    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert" style="color: black;">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        </div>
    {% endfor %}

    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light ">
        <div class="portlet-body">
            <div class="tiles">
                <div class="tile bg-green-turquoise" style="height: 170px !important;width: 50% !important;">
                    <a href="{% url 'parent_portal:student_list' %}">
                        <div class="tile-body">
                                <i class="fa fa-id-card" aria-hidden="true"></i>
                        </div>
                        <div class="tile-object">
                            <div class="name text-success"><h4>Student Profile</h4></div>
                        </div>
                    </a>
                </div>

                <div class="tile bg-blue" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'parent_portal:view_update_parent' %}">
                        <div class="tile-body">
                                <i class="fa fa-id-card" aria-hidden="true"></i>
                        </div>
                        <div class="tile-object">
                            <div class="name "><h4>Parent Profile</h4></div>

                        </div>
                    </a>
                </div>

{#                <div class="tile double-down bg-purple-studio" style="height: 170px !important;width: 48% !important;">#}
{#                    <a href="{% url 'id_generation:view_staff_list' %}">#}
{##}
{#                        <div class="tile-body">#}
{#                            <i class="fa fa-id-badge " aria-hidden="true"></i>#}
{##}
{#                        </div>#}
{#                        <div class="tile-object">#}
{#                            <div class="name "><h4  >Staff ID Cards</h4></div>#}
{##}
{#                        </div>#}
{#                    </a>#}
{#                </div>#}
{##}
{#                <div class="tile bg-blue-hoki" style="height: 170px !important;width: 48% !important;">#}
{#                    <a href="{% url 'id_generation:staff_template' %}">#}
{##}
{#                        <div class="tile-body">#}
{#                            <i class="fa fa-id-badge " aria-hidden="true"></i>#}
{##}
{#                        </div>#}
{#                        <div class="tile-object">#}
{#                            <div class="name "><h4  >Staff ID Card - Template</h4></div>#}
{##}
{#                        </div>#}
{#                    </a>#}
{#                </div>#}

            </div>
        </div>
    </div>
{% endblock %}