edsys_assesment/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import registration.urls
import transfer_certificate.urls
import strike_off.urls
import id_generation.urls
import medical.urls
import attendance.urls
import password_reset.urls
import masters.urls
import promotions.urls
import assessment.urls
import parent_portal.urls
import rest_api.urls
from registration import views
import os
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    url(r'^api/', include(rest_api.urls, namespace='api')),
    url(r'^school/', include(registration.urls, namespace='registration')),
    url(r'^$', views.Login, name='login'),
    url(r'^school/', include(transfer_certificate.urls, namespace='transfer_certificate')),
    url(r'^school/', include(strike_off.urls, namespace='strike_off')),
    url(r'^school/', include(id_generation.urls, namespace='id_generation')),
    url(r'^school/', include(medical.urls, namespace='medical')),
    url(r'^school/', include(password_reset.urls, namespace='password_reset')),
    url(r'^school/', include(attendance.urls, namespace='attendance')),
    url(r'^school/', include(masters.urls, namespace='masters')),
    url(r'^school/', include(promotions.urls, namespace='promotions')),
    url(r'^school/', include(assessment.urls, namespace='assessment')),
    url(r'^school/', include(parent_portal.urls, namespace='parent_portal')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('social_django.urls', namespace='social')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^sso/', include("djssoserver.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ADMIN_URL_ENABLE:
    urlpatterns.append(url(r'^admin/', admin.site.urls))

masters/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static

app_name = 'masters'

urlpatterns = [

                  ########=================================odoo configuration======================================================
                  url(r'^template_odoo_config_list/$', views.TemplateOdooConfigList, name='template_odoo_config_list'),
                  url(r'^add_odoo_config/$', views.AddOdooConfig, name='add_odoo_config'),
                  url(r'^template_update_config/(?P<config_id>[0-9]+)$', views.TemplateUpdateOdooConfig,
                      name='template_update_config'),
                  url(r'^update_odoo_config/$', views.UpdateOdooConfig, name='update_odoo_config'),
                  url(r'^test_connection/$', views.TestOdooConnection, name='test_connection'),
                  url(r'^start_syncing/$', views.StartOdooSync, name='start_syncing'),
                  url(r'^sync_switch/$', views.OdooSyncOnOff, name='sync_switch'),
                  #=================================================================================================================

                  url(r'^month_masters/$', views.MonthMasters, name='month_masters'),

                  url(r'^masters_home/$', views.ManageMasters, name='masters_home'),
                  url(r'^data_access/$', views.DataAccessMasters, name='data_access'),
                  url(r'^religion_masters/$', views.ManageReligionMasters, name='religion_masters'),
                  url(r'^add_religion_masters/$', views.AddReligionMasters, name='add_religion_masters'),
                  url(r'^update_religion/(?P<religion_id>[0-9]+)$', views.UpdateReligion, name='update_religion'),
                  url(r'^save_updated_religion/$', views.SaveUpdatedReligion, name='save_updated_religion'),
                  url(r'^delete_religion/(?P<religion_id>[0-9]+)$', views.DeleteReligion, name='delete_religion'),

                  # =-==-=-=-=-==-=-=-Nationality Urls=-=-=-====-=-=-=-=

                  url(r'^nationality_masters/$', views.ManageNationalityMasters, name='nationality_masters'),
                  url(r'^add_nationality_masters/$', views.AddNationalityMasters, name='add_nationality_masters'),
                  url(r'^update_nationality/(?P<nationality_id>[0-9]+)$', views.UpdateNationality,
                      name='update_nationality'),
                  url(r'^save_updated_nationality/$', views.SaveUpdatedNationality, name='save_updated_nationality'),
                  url(r'^delete_nationality/(?P<nationality_id>[0-9]+)$', views.DeleteNationality,
                      name='delete_nationality'),

                  # =-=-=-=-=-=-=-=-=-=--Department Master Urls=-=-=-=-=-=-=-=-=-=-
                  url(r'^department_master/$', views.ManageDepartment, name='department_master'),
                  url(r'^add_department_masters/$', views.AddDepartmentMasters, name='add_department_masters'),
                  url(r'^update_department/(?P<department_id>[0-9]+)$', views.UpdateDepartment,
                      name='update_department'),
                  url(r'^save_updated_department/$', views.SaveUpdatedDepartment, name='save_updated_department'),
                  url(r'^delete_department/(?P<department_id>[0-9]+)$', views.DeleteDepartment,
                      name='delete_department'),

                  # =-==-=-=-=-==-=-=-Exam Urls=-=-=-====-=-=-=-=

                  url(r'^exam_masters/$', views.ManageExamMasters, name='exam_masters'),
                  url(r'^add_exam_masters/$', views.AddExamMasters, name='add_exam_masters'),
                  url(r'^update_exam/(?P<exam_type_id>[0-9]+)$', views.UpdateExam,
                      name='update_exam'),
                  url(r'^save_updated_exam/$', views.SaveUpdatedExam, name='save_updated_exam'),
                  url(r'^delete_exam/(?P<exam_type_id>[0-9]+)$', views.DeleteExam,
                      name='delete_exam'),

                  # =-==-=-=-=-==-=-=-Rubrics Urls=-=-=-====-=-=-=-=

                  url(r'^rubrics_masters/$', views.RubricsMasters, name='rubrics_masters'),
                  url(r'^add_rubrics_masters/$', views.AddRubricsMasters, name='add_rubrics_masters'),
                  url(r'^update_rubrics/(?P<rubrics_id>[0-9]+)$', views.UpdateRubrics,
                      name='update_rubrics'),
                  url(r'^save_updated_rubrics/$', views.SaveUpdatedRubrics, name='save_updated_rubrics'),
                  url(r'^delete_rubrics/(?P<rubrics_id>[0-9]+)$', views.DeleteRubrics,
                      name='delete_rubrics'),

                  url(r'^rubrics_category/$', views.RubricsCategory, name='rubrics_category'),
                  url(r'^add_rubrics_category/$', views.AddRubricsCategory, name='add_rubrics_category'),
                  url(r'^update_rubrics_catgory/(?P<rubrics_category_id>[0-9]+)$', views.UpdateRubricsCategory,
                      name='update_rubrics_catgory'),
                  url(r'^save_updated_rubrics_category/$', views.SaveUpdatedRubricsCategory,
                      name='save_updated_rubrics_category'),
                  url(r'^delete_rubrics_category/(?P<rubrics_category_id>[0-9]+)$', views.DeleteRubricsCategory,
                      name='delete_rubrics_category'),

                  url(r'^nationality_group/$', views.NationalityGroup, name='nationality_group'),
                  url(r'^add_nationality_group/$', views.AddNationalityGroup, name='add_nationality_group'),

                  url(r'^update_nationality_group/(?P<nationality_group_id>[0-9]+)$', views.UpdateNationalityGroup,
                      name='update_nationality_group'),
                  url(r'^save_updated_nationality_group/$', views.SaveUpdatedNationalityGroup,
                      name='save_updated_nationality_group'),

                  url(r'^delete_nationality_group/(?P<nationality_group_id>[0-9]+)$', views.DeleteNationalityGroup,
                      name='delete_nationality_group'),

                  # =-==-=-=-=-==-=-=-Home Urls=-=-=-====-=-=-=-=
                  url(r'^house_master_list/$', views.HouseMasterList, name='house_master_list'),
                  url(r'^add_house/$', views.AddHouse, name='add_house'),
                  url(r'^update_hose/(?P<house_id>[0-9]+)$', views.UpdateHose,
                      name='update_hose'),
                  url(r'^save_updated_house/$', views.SaveUpdatedHouse, name='save_updated_house'),
                  url(r'^delete_house/(?P<house_id>[0-9]+)$', views.DeleteHouse,
                      name='delete_house'),

                  url(r'^nationality_group_mapping/$', views.NationalityGroupMapping, name='nationality_group_mapping'),

                  url(r'^group_nationality_mapping/$', views.GroupNationalityMapping, name='group_nationality_mapping'),
                  url(r'^save_group_nationality_mapping/$', views.SaveGroupNationalityMapping,
                      name='save_group_nationality_mapping'),
                  url(r'^delete_group_nationality_mapping/$', views.DeleteGroupNationalityMapping,
                      name='delete_group_nationality_mapping'),

                  url(r'^tc_type_master/$', views.TCTYPEMASTER, name='tc_type_master'),

                  # =-==-=-=-=-==-=-=-Assessment Configration Urls=-=-=-====-=-=-=-=

                  url(r'^assessment_configration/$', views.AssessmentConfigration, name='assessment_configration'),
                  url(r'^add_assessment_configration/$', views.AddAssessmentConfigration,
                      name='add_assessment_configration'),
                  url(r'^update_assessment_configration/(?P<ass_config_id>[0-9]+)$', views.UpdateAssessmentConfigration,
                      name='update_assessment_configration'),

                  url(r'^save_updated_assessment_configraton/$', views.SaveUpdatedAssessmentConfigraton,
                      name='save_updated_assessment_configraton'),
                  url(r'^delete_assessment_configration/(?P<ass_config_id>[0-9]+)$', views.DeleteAssessmentConfigration,
                      name='delete_assessment_configration'),

                  url(r'^assessment_configrtion_roundoff/$', views.AssessmentConfigrtionRoundOff,
                      name='assessment_configrtion_roundoff'),

                  url(r'^assessment_round_off/$', views.AssessmentRoundOff, name='assessment_round_off'),
                  url(r'^add_round_off/$', views.AddRoundOff, name='add_round_off'),
                  # url(r'^round_off_list/$', views.RoundOffList, name='round_off_list'),
                  url(r'^update_round_off/', views.UpdateRoundOff,
                      name='update_round_off'),
                  url(r'^save_updated_round_off/$', views.SaveUpdatedRoundOff, name='save_updated_round_off'),
                  url(r'^delete_round_off/(?P<round_off_id>[0-9]+)$', views.DeleteRoundOff,
                      name='delete_round_off'),
                  url(r'^active_round/$', views.ActiveRound, name='active_round'),
                  url(r'^inactive_round/$', views.InActiveRound, name='inactive_round'),

                  # ============== Section Type ============================

                  url(r'^section_type_master/$', views.SectionTypeMaster, name='section_type_master'),
                  url(r'^add_section_type/$', views.AddSectionType, name='add_section_type'),
                  url(r'^save_section_type/$', views.SaveSectionType, name='save_section_type'),
                  url(r'^update_section_type/(?P<type_id>[0-9]+)$', views.UpdateSectionType,name='update_section_type'),
                  url(r'^save_updated_section_type/$', views.SaveUpdateSectionType, name='save_updated_section_type'),
                  url(r'^delete_section_type/(?P<type_id>[0-9]+)$', views.DeleteSectionType, name='delete_section_type'),

transfer_certificate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static, serve

app_name = 'transfer_certificate'


urlpatterns = [
    
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

######################################### TC Details ###################################  
    url(r'^tc_detail/$',views.TCDetail, name='tc_detail'),  
    url(r'^apply_tc/$',views.ApplyTc, name='apply_tc'), 
    url(r'^filter_tc_apply/$',views.FilterApplyTc, name='filter_tc_apply'),
    url(r'^request_tc_form/$',views.RequestTcForm, name='request_tc_form'),
    url(r'^save_tc_form/$',views.SaveTCRequest, name='save_tc_form'), 
    url(r'^requested_tc_list/$',views.RequestedTcList, name='requested_tc_list'), 
    url(r'^grant_tc/$',views.GrantTC, name='grant_tc'),
    url(r'^view_alumni/$',views.ViewAlumni, name='view_alumni'),
    url(r'^view_alumni_list/$',views.ViewAlumniList, name='view_alumni_list'),
    url(r'^generate_tc/$',views.GenerateTc, name='generate_tc'),
    url(r'^reject_tc/$',views.RejectTC, name='reject_tc'),
    url(r'^reverse_tc/$',views.ReverseTC, name='reverse_tc'),
    url(r'^approve_reversal/$',views.ApproveReversal, name='approve_reversal'),
    url(r'^reject_reversal/$',views.RejectReversal, name='reject_reversal'),
    url(r'^export_tc/$',views.ExportTC, name='export_tc'),
    url(r'^export_tc_rec/$',views.ExportTCRec, name='export_tc_rec'),
    #url(r'^view_student_list/$',views.ViewStudentList, name='view_student_list'),
    url(r'^export_transfer_certificate/$',views.ExportTransferCertificate, name='export_transfer_certificate'),
    url(r'^student_details/(?P<std_id>[0-9]+)$', views.StudentDetails, name='student_details'),

        
   ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

transfer_certificate/models.py
from __future__ import unicode_literals
from registration.models import student_details
from django.db import models
from datetime import datetime

# Create your models here.
inside_dubai = (
                    ('yes', ("yes")),
                    ('no', ("no")),
                )

inside_uae = (
                    ('yes', ("yes")),
                    ('no', ("no")),
                )

class TcDetails(models.Model):
    leaving_reason = models.CharField(max_length = 255)
    inside_dubai = models.CharField(max_length=3, choices = inside_dubai)
    inside_uae = models.CharField(max_length=3, choices = inside_uae)
    curriculam = models.CharField(max_length = 45,null=True, blank=True)
    is_confirm = models.BooleanField(default=False)
    # is_reversal_approved = models.BooleanField(blank = True)
    is_reversal_approved = models.BooleanField(default=False)
    create_date = models.DateTimeField(default = datetime.now)
    update_date = models.DateTimeField(default = datetime.now)

    school_name = models.CharField(max_length = 255)
    student = models.ForeignKey(student_details)

    class Meta:
        permissions = (
            ('can_view_transfer_certificate', 'can view transfer certificate'),
            ('can_view_transfer_certificate_apply', 'can view transfer certificate apply'),
            ('can_view_transfer_certificate_view_confirm', 'can view transfer certificate view confirm'),
            ('can_view_transfer_certificate_view_alumni', 'can view transfer certificate alumni'),
            ('can_view_transfer_certificate_export_tc', 'can view transfer certificate export tc'),
        )

transfer_certificate/forms.py
from django import forms
from transfer_certificate.models import TcDetails
from datetime import datetime

inside_dubai = (
                    ('yes', ("yes")),
                    ('no', ("no")),
                )

inside_uae = (
                    ('yes', ("yes")),
                    ('no', ("no"))
              )

class TCDetailsForm(forms.ModelForm):
    student_id = forms.CharField(widget = forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    leaving_reason = forms.CharField(required = True,widget = forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off', 'maxlength':'255'}))
    inside_dubai = forms.TypedChoiceField(choices = inside_dubai, required = True, widget=forms.RadioSelect )
    inside_uae = forms.TypedChoiceField(choices = inside_uae, widget=forms.RadioSelect )
    # curriculam = forms.CharField(widget = forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off'}))
    school_name = forms.CharField(required=True, widget = forms.TextInput(attrs={'class':'form-control' , 'autocomplete': 'off', 'maxlength':'255'}))
    class Meta:
        model = TcDetails
        fields =['student_id','leaving_reason','inside_dubai','inside_uae','school_name']

transfer_certificate/templates/request_tc_form.html
{% extends "index.html" %}
{% load staticfiles %}

         {%block styleBlock%}
      <style type="text/css">  
        .row {
    margin-left: 80px;
    margin-right: 20px;
    margin-top: 0px;
}
li
{ 
display:inline; 

} 
#id_inside_dubai{
    list-style: none;
}

#id_inside_uae{
    list-style: none;
}
      </style> 
        {%endblock%}
        
        {%block ScriptBlock%}
<script>
window.onload = function() 
{
	  //YOUR JQUERY CODE
	$(document).ready(function() 
	  {
		console.log("hiiii")
	
		$("#save1").click(function(event){
		    var reason = $("#id_leaving_reason").val();

		    if( /[^a-zA-Z\-\/ ]+/.test( reason ) ) {
		        alert('Input is not characters');
		        return false;
		    }
		    if ((reason.trim().length) == 0)
            {
                alert(' Please Enter Reason. Only Space is not allowed in reason');
		        return false;
            }

		    var curr = $("#id_curriculam").val();

		    if( /[^a-zA-Z\-\/ ]+/.test( curr ) ) {
		        alert('Input is not characters');
		        return false;
		    }

		    if ((curr.trim().length) == 0)
            {
                alert('  Please enter curriculam. Only Space is not allowed in curriculam');
		        return false;
            }
{#			            alert("2")#}

		    var school = $("#id_school_name").val();

		    if( /[^a-zA-Z\-\/ ]+/.test( school ) ) {
		        alert('Input is not characters');
		        return false;
		    }

		    if(document.getElementById('id_school_name').disabled == false) {
                if ((school.trim().length) == 0) {
                    alert('Please enter  name. Only Space is not allowed in school name');
                    return false;
                }
            }
	    });
		
		$("#id_leaving_reason").change(function(){

			var reason = $("#id_leaving_reason").val();

		    if( /[^a-zA-Z\-\/ ]+/.test( reason ) ) {
		        alert('Input is not characters');
		        return false;
		    }

		    return true;   
		});
		
		$("#id_curriculam").change(function(){

			var curr = $("#id_curriculam").val();

		    if( /[^a-zA-Z\-\/ ]+/.test( curr ) ) {
		        alert('Input is not characters');
		        return false;
		    }

		    return true;   
		});
		
		
		
		
		$('input:radio[name="inside_uae"]').filter('[value="no"]').attr('checked', true);
		
		
		$("#id_inside_dubai").click(function(){
		a = $('input[name=inside_dubai]:checked').val();

		if(a=="no"){
            $('#id_school_name').prop("disabled", false);
			$("#div1").show();
{#			$("#div2").show();#}

		}
		 else {
{#		    $('#id_school_name').prop("disabled", true);#}
             $("#div1").hide();
{#             $("#div2").hide();#}
         }

		});
	  
	  });
	
	
	
}
</script>

{%endblock%}       
       
        {% block content %}
        

{% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert" style="color: black;" >{{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    </div>
{% endfor %}
<div class="page-bar" style="margin-bottom: 1px;">
                        <ul class="page-breadcrumb">
                            <li>
                                <i class="icon-home"></i>
                               <a href="{% url 'registration:home' %}">Home</a> 
                                <i class="fa fa-angle-right"></i>
                            </li>
{#                            <li>#}
{#                                #}
{#                                <a href="{% url 'registration:parents_students' %}"> Parents & Students</a>#}
{#                                <i class="fa fa-angle-right"></i>#}
{#                            </li>#}
							
                            <li>
                                
                                <a href="{% url 'transfer_certificate:apply_tc' %}"> Request TC</a>
                                
                            </li>


                            
                        </ul>
                        
                    </div>
                            <!-- BEGIN VALIDATION STATES-->
                            <div class="portlet light portlet-fit portlet-form ">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="icon-settings font-red"></i>
                                        <span class="caption-subject font-red sbold uppercase">Request Transfer certificate</span>
                                    </div>
                                    
                                </div>
                                <div class="portlet-body">
                                
                               
                                   
										
										
										
										<form action="{% url 'transfer_certificate:save_tc_form' %}" id="form_sample_1" class="form-horizontal" method="POST">
                                    
                                    
                                   
										{% csrf_token %}
                                   
                                        <div class="form-body">
                                              
                                              
                                            
                                            <br>
                                            <div class="row">
                                            <div class="">
                                            <input id="check" name="check" type="hidden" value="{{ check }}">
                                                <label class="col-md-3 control-label">Reason for Leaving:
                                                   
                                                </label>
                                                <div class="col-md-4">
                                                    {{ TCForm.leaving_reason }} </div>
                                            </div>
                                            </div>
                                            <br>
                                           
                                           
                                           <div class="row">
{#                                            #}
{#                                            <div class="">#}
{#                                            <label class="col-md-3 control-label">Curriculam:#}
{#                                                   #}
{#                                                </label>#}
{#                                                <div class="col-md-4" >#}
{#                                                    {{ TCForm.curriculam }} </div>#}
{#                                            </div>#}
                                            </div>
                                            <br>
                                            <div class="row">
                                            <div class="">
                                            <label class="col-md-3 control-label">Inside Dubai:
                                                   
                                                </label>
                                                 <div class="col-md-4" style="margin-left:-39px;margin-top: 3px;">
                                                    {{ TCForm.inside_dubai }} </div>
                                            </div>
                                            
                                              
                                            </div>
                                            <br>
                                            <div class="row" id="div1">
                                            <div class="">
                                                <label class="col-md-3 control-label">Inside UAE:
                                                    
                                                </label>
                                                 <div class="col-md-4" style="margin-left:-39px;margin-top: 3px;">
                                                  {{ TCForm.inside_uae }}
                                                 </div>
                                            </div> 
                                            </div>
                                            <br>
                                            
                                            
                                            
                                            <div class="row" id="div2">
                                            <div class="">
                                            <label class="col-md-3 control-label" value="">New School Name:
                                                   
                                                </label>
                                                 <div class="col-md-4">
                                                    {{ TCForm.school_name }} </div>
                                            </div>
                                            
                                              
                                            </div>
                                            
                                            <br><br>
                                        
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <button id="save1" type="submit" class="btn green">Submit</button>
                                                   	<button onclick="window.location.href='{% url "transfer_certificate:apply_tc" %}'" type="button" class="btn green">Cancel</button>
                                                </div>
                                            </div>
                                        
                                      </div>   
                                       <br>
                                          
                                    </form>
                                    <!-- END FORM-->
                                </div>
                            </div>
                            <!-- END VALIDATION STATES-->
                       
                       
           {% endblock %}  