edsys_assesment/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import registration.urls
import transfer_certificate.urls
import strike_off.urls
import id_generation.urls
import medical.urls
import attendance.urls
import password_reset.urls
import masters.urls
import promotions.urls
import assessment.urls
import parent_portal.urls
import rest_api.urls
from registration import views
import os
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    url(r'^api/', include(rest_api.urls, namespace='api')),
    url(r'^school/', include(registration.urls, namespace='registration')),
    url(r'^$', views.Login, name='login'),
    url(r'^school/', include(transfer_certificate.urls, namespace='transfer_certificate')),
    url(r'^school/', include(strike_off.urls, namespace='strike_off')),
    url(r'^school/', include(id_generation.urls, namespace='id_generation')),
    url(r'^school/', include(medical.urls, namespace='medical')),
    url(r'^school/', include(password_reset.urls, namespace='password_reset')),
    url(r'^school/', include(attendance.urls, namespace='attendance')),
    url(r'^school/', include(masters.urls, namespace='masters')),
    url(r'^school/', include(promotions.urls, namespace='promotions')),
    url(r'^school/', include(assessment.urls, namespace='assessment')),
    url(r'^school/', include(parent_portal.urls, namespace='parent_portal')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('social_django.urls', namespace='social')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^sso/', include("djssoserver.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ADMIN_URL_ENABLE:
    urlpatterns.append(url(r'^admin/', admin.site.urls))

masters/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static

app_name = 'masters'

urlpatterns = [

                  ########=================================odoo configuration======================================================
                  url(r'^template_odoo_config_list/$', views.TemplateOdooConfigList, name='template_odoo_config_list'),
                  url(r'^add_odoo_config/$', views.AddOdooConfig, name='add_odoo_config'),
                  url(r'^template_update_config/(?P<config_id>[0-9]+)$', views.TemplateUpdateOdooConfig,
                      name='template_update_config'),
                  url(r'^update_odoo_config/$', views.UpdateOdooConfig, name='update_odoo_config'),
                  url(r'^test_connection/$', views.TestOdooConnection, name='test_connection'),
                  url(r'^start_syncing/$', views.StartOdooSync, name='start_syncing'),
                  url(r'^sync_switch/$', views.OdooSyncOnOff, name='sync_switch'),
                  #=================================================================================================================

                  url(r'^month_masters/$', views.MonthMasters, name='month_masters'),

                  url(r'^masters_home/$', views.ManageMasters, name='masters_home'),
                  url(r'^data_access/$', views.DataAccessMasters, name='data_access'),
                  url(r'^religion_masters/$', views.ManageReligionMasters, name='religion_masters'),
                  url(r'^add_religion_masters/$', views.AddReligionMasters, name='add_religion_masters'),
                  url(r'^update_religion/(?P<religion_id>[0-9]+)$', views.UpdateReligion, name='update_religion'),
                  url(r'^save_updated_religion/$', views.SaveUpdatedReligion, name='save_updated_religion'),
                  url(r'^delete_religion/(?P<religion_id>[0-9]+)$', views.DeleteReligion, name='delete_religion'),

                  # =-==-=-=-=-==-=-=-Nationality Urls=-=-=-====-=-=-=-=

                  url(r'^nationality_masters/$', views.ManageNationalityMasters, name='nationality_masters'),
                  url(r'^add_nationality_masters/$', views.AddNationalityMasters, name='add_nationality_masters'),
                  url(r'^update_nationality/(?P<nationality_id>[0-9]+)$', views.UpdateNationality,
                      name='update_nationality'),
                  url(r'^save_updated_nationality/$', views.SaveUpdatedNationality, name='save_updated_nationality'),
                  url(r'^delete_nationality/(?P<nationality_id>[0-9]+)$', views.DeleteNationality,
                      name='delete_nationality'),

                  # =-=-=-=-=-=-=-=-=-=--Department Master Urls=-=-=-=-=-=-=-=-=-=-
                  url(r'^department_master/$', views.ManageDepartment, name='department_master'),
                  url(r'^add_department_masters/$', views.AddDepartmentMasters, name='add_department_masters'),
                  url(r'^update_department/(?P<department_id>[0-9]+)$', views.UpdateDepartment,
                      name='update_department'),
                  url(r'^save_updated_department/$', views.SaveUpdatedDepartment, name='save_updated_department'),
                  url(r'^delete_department/(?P<department_id>[0-9]+)$', views.DeleteDepartment,
                      name='delete_department'),

                  # =-==-=-=-=-==-=-=-Exam Urls=-=-=-====-=-=-=-=

                  url(r'^exam_masters/$', views.ManageExamMasters, name='exam_masters'),
                  url(r'^add_exam_masters/$', views.AddExamMasters, name='add_exam_masters'),
                  url(r'^update_exam/(?P<exam_type_id>[0-9]+)$', views.UpdateExam,
                      name='update_exam'),
                  url(r'^save_updated_exam/$', views.SaveUpdatedExam, name='save_updated_exam'),
                  url(r'^delete_exam/(?P<exam_type_id>[0-9]+)$', views.DeleteExam,
                      name='delete_exam'),

                  # =-==-=-=-=-==-=-=-Rubrics Urls=-=-=-====-=-=-=-=

                  url(r'^rubrics_masters/$', views.RubricsMasters, name='rubrics_masters'),
                  url(r'^add_rubrics_masters/$', views.AddRubricsMasters, name='add_rubrics_masters'),
                  url(r'^update_rubrics/(?P<rubrics_id>[0-9]+)$', views.UpdateRubrics,
                      name='update_rubrics'),
                  url(r'^save_updated_rubrics/$', views.SaveUpdatedRubrics, name='save_updated_rubrics'),
                  url(r'^delete_rubrics/(?P<rubrics_id>[0-9]+)$', views.DeleteRubrics,
                      name='delete_rubrics'),

                  url(r'^rubrics_category/$', views.RubricsCategory, name='rubrics_category'),
                  url(r'^add_rubrics_category/$', views.AddRubricsCategory, name='add_rubrics_category'),
                  url(r'^update_rubrics_catgory/(?P<rubrics_category_id>[0-9]+)$', views.UpdateRubricsCategory,
                      name='update_rubrics_catgory'),
                  url(r'^save_updated_rubrics_category/$', views.SaveUpdatedRubricsCategory,
                      name='save_updated_rubrics_category'),
                  url(r'^delete_rubrics_category/(?P<rubrics_category_id>[0-9]+)$', views.DeleteRubricsCategory,
                      name='delete_rubrics_category'),

                  url(r'^nationality_group/$', views.NationalityGroup, name='nationality_group'),
                  url(r'^add_nationality_group/$', views.AddNationalityGroup, name='add_nationality_group'),

                  url(r'^update_nationality_group/(?P<nationality_group_id>[0-9]+)$', views.UpdateNationalityGroup,
                      name='update_nationality_group'),
                  url(r'^save_updated_nationality_group/$', views.SaveUpdatedNationalityGroup,
                      name='save_updated_nationality_group'),

                  url(r'^delete_nationality_group/(?P<nationality_group_id>[0-9]+)$', views.DeleteNationalityGroup,
                      name='delete_nationality_group'),

                  # =-==-=-=-=-==-=-=-Home Urls=-=-=-====-=-=-=-=
                  url(r'^house_master_list/$', views.HouseMasterList, name='house_master_list'),
                  url(r'^add_house/$', views.AddHouse, name='add_house'),
                  url(r'^update_hose/(?P<house_id>[0-9]+)$', views.UpdateHose,
                      name='update_hose'),
                  url(r'^save_updated_house/$', views.SaveUpdatedHouse, name='save_updated_house'),
                  url(r'^delete_house/(?P<house_id>[0-9]+)$', views.DeleteHouse,
                      name='delete_house'),

                  url(r'^nationality_group_mapping/$', views.NationalityGroupMapping, name='nationality_group_mapping'),

                  url(r'^group_nationality_mapping/$', views.GroupNationalityMapping, name='group_nationality_mapping'),
                  url(r'^save_group_nationality_mapping/$', views.SaveGroupNationalityMapping,
                      name='save_group_nationality_mapping'),
                  url(r'^delete_group_nationality_mapping/$', views.DeleteGroupNationalityMapping,
                      name='delete_group_nationality_mapping'),

                  url(r'^tc_type_master/$', views.TCTYPEMASTER, name='tc_type_master'),

                  # =-==-=-=-=-==-=-=-Assessment Configration Urls=-=-=-====-=-=-=-=

                  url(r'^assessment_configration/$', views.AssessmentConfigration, name='assessment_configration'),
                  url(r'^add_assessment_configration/$', views.AddAssessmentConfigration,
                      name='add_assessment_configration'),
                  url(r'^update_assessment_configration/(?P<ass_config_id>[0-9]+)$', views.UpdateAssessmentConfigration,
                      name='update_assessment_configration'),

                  url(r'^save_updated_assessment_configraton/$', views.SaveUpdatedAssessmentConfigraton,
                      name='save_updated_assessment_configraton'),
                  url(r'^delete_assessment_configration/(?P<ass_config_id>[0-9]+)$', views.DeleteAssessmentConfigration,
                      name='delete_assessment_configration'),

                  url(r'^assessment_configrtion_roundoff/$', views.AssessmentConfigrtionRoundOff,
                      name='assessment_configrtion_roundoff'),

                  url(r'^assessment_round_off/$', views.AssessmentRoundOff, name='assessment_round_off'),
                  url(r'^add_round_off/$', views.AddRoundOff, name='add_round_off'),
                  # url(r'^round_off_list/$', views.RoundOffList, name='round_off_list'),
                  url(r'^update_round_off/', views.UpdateRoundOff,
                      name='update_round_off'),
                  url(r'^save_updated_round_off/$', views.SaveUpdatedRoundOff, name='save_updated_round_off'),
                  url(r'^delete_round_off/(?P<round_off_id>[0-9]+)$', views.DeleteRoundOff,
                      name='delete_round_off'),
                  url(r'^active_round/$', views.ActiveRound, name='active_round'),
                  url(r'^inactive_round/$', views.InActiveRound, name='inactive_round'),

                  # ============== Section Type ============================

                  url(r'^section_type_master/$', views.SectionTypeMaster, name='section_type_master'),
                  url(r'^add_section_type/$', views.AddSectionType, name='add_section_type'),
                  url(r'^save_section_type/$', views.SaveSectionType, name='save_section_type'),
                  url(r'^update_section_type/(?P<type_id>[0-9]+)$', views.UpdateSectionType,name='update_section_type'),
                  url(r'^save_updated_section_type/$', views.SaveUpdateSectionType, name='save_updated_section_type'),
                  url(r'^delete_section_type/(?P<type_id>[0-9]+)$', views.DeleteSectionType, name='delete_section_type'),

masters/models.py
from __future__ import unicode_literals

from django.db import models

# from registration.models import nationality
# from registration.models import *


# Create your models here.

class exam_type(models.Model):
    exam_type_name = models.CharField(max_length=250)

    def __unicode__(self):
        return self.exam_type_name

class section_type_details(models.Model):
    section_type_name = models.CharField(max_length=80)

    def __unicode__(self):
        return self.section_type_name



class rubrics_category(models.Model):
    rubric_catgory = models.CharField(max_length=100)

    def __unicode__(self):
        return self.rubric_catgory



class rubrics_master(models.Model):
    rubrics_name = models.CharField(max_length=100)
    rubrics_mark = models.CharField(max_length=5)
    rubrics_category_name = models.ForeignKey(rubrics_category, on_delete=models.PROTECT, null=True)

    def __unicode__(self):
        return self.rubrics_name


class nationality_group(models.Model):
    nationatity_group_name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.nationatity_group_name

class house_master(models.Model):
    house_name = models.CharField(max_length=250)

    def __unicode__(self):
        return self.house_name

class nationality_group_mapping(models.Model):
    nationality_group_name = models.ForeignKey(nationality_group, on_delete=models.PROTECT, null=True)
    nationality_mapping_name = models.ForeignKey('registration.nationality', on_delete=models.PROTECT, null=True)


    # def __unicode__(self):
    #     return self.nationality_group_name


class tc_type(models.Model):
    tc_type_name = models.CharField(max_length=260)

    def __unicode__(self):
        return self.tc_type_name



class assessment_configration_master(models.Model):
    configration_name = models.CharField(max_length=250)
    short_name = models.CharField(max_length=100,blank=True, null=True)
    select = models.CharField(max_length=25,blank=True, null=True)

    def __unicode__(self):
        return self.configration_name


class assessment_round_master(models.Model):
    select = models.BooleanField(default=True)
    decimal_place = models.CharField(max_length=10)

class report_card_conf(models.Model):
    url = models.CharField(max_length=80, blank=True, null=True)
    user_name = models.CharField(max_length=80, blank=True, null=True)
    port = models.CharField(max_length=80, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

class report_card_term_details(models.Model):
    report_card_term_name = models.CharField(max_length=80,blank=True, null=True)

    def __unicode__(self):
        return self.report_card_term_name


class OdooConfiguration(models.Model):
    odoo_ip_address = models.CharField(max_length=100,null=True,blank=True)
    odoo_server_port = models.CharField(max_length=10,null=True,blank=True)
    odoo_db_name = models.CharField(max_length=100,null=True,blank=True)
    odoo_db_username = models.CharField(max_length=100,null=True,blank=True)
    odoo_db_password = models.CharField(max_length=100,null=True,blank=True)
    is_config_active = models.BooleanField(default=False)

    def __unicode__(self):
        return self.odoo_ip_address

masters/templates/add_nationality_master.html
{% extends "index.html" %}
{% load staticfiles %}
{% block ScriptBlock %}
    <Script>
        window.onload = function () {
            //YOUR JQUERY CODE
            $(document).ready(function () {
                console.log("hiiii")
                $("#save1").click(function (event) {

                    var reason = $("#id_nationality_name").val();

                    if (/[^a-zA-Z\-\/ ]+/.test(reason)) {
                        alert('Input characters only');
                        return false;
                    }

                    if ((reason.trim().length) == 0) {
                        alert('Input characters only');
                        return false;
                    }

                });

                $("#id_nationality_name").change(function () {

                    var reason = $("#id_nationality_name").val();

                    if (/[^a-zA-Z\-\/ ]+/.test(reason)) {
                        alert('Input characters only');
                        return false;
                    }
                    if ((reason.trim().length) == 0) {
                        alert('Input characters only');
                        return false;
                    }


                    return true;
                });


            });
        }

    </Script>

{% endblock %}

{% block content %}

    <div class="page-bar" style="margin-bottom: 1px;">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{% url 'registration:home' %}">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>

                <a href="{% url 'masters:masters_home' %}">Masters</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>

                <a href="{% url 'masters:nationality_masters' %}"> Nationality Master </a>
                <i class="fa fa-angle-right"></i>
            </li>

            <li>
                <span>Add Nationality</span>
                {#                                <i class="fa fa-angle-right"></i>#}
            </li>
        </ul>

    </div>


    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert" style="color: black;">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        </div>
    {% endfor %}



    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light portlet-fit portlet-form ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-settings font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Add Nationality</span>
            </div>

        </div>
        <div class="portlet-body">


            <!-- BEGIN FORM-->
            <form action="{% url 'masters:add_nationality_masters' %}" id="form_sample_1" class="form-horizontal"
                  method="POST" enctype="multipart/form-data">


                {% csrf_token %}

                <div class="form-body">

                    <div class="row">

{#                        <div class="">#}
{#                            <label class="col-md-2 control-label">Nationality Group Name:#}
{##}
{#                            </label>#}
{#                                <div class="col-md-3">#}
{#                                        {{ form.nationality_group_name }}#}
{#                                </div>#}
{#                        </div>#}


                        <div class="">
                            <label class="col-md-2 control-label"> Nationality:

                            </label>
                            <div class="col-md-4">
                                {{ form.nationality_name }}
                            </div>
                        </div>
                        {#                                                <div class="">#}
                        {#                                                    <label class="col-md-2 control-label">Religion:#}
                        {#                                                       #}
                        {#                                                    </label>#}
                        {#                                                        <div class="col-md-4">#}
                        {#                                                                {{ AbsentreasonForm.absent_reason }}#}
                        {#                                                        </div>#}
                        {#                                                </div>#}


                    </div>
                    <br><br>


                </div>
                <br>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" id="save1" class="btn green">Save</button>
                            <a href="{% url 'masters:nationality_masters' %}">
                                <button type="button" class="btn grey-salsa btn-outline">Cancel</button>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
            <!-- END FORM-->
        </div>
    </div>
    <!-- END VALIDATION STATES-->


{% endblock %}

<!-- BEGIN CORE PLUGINS -->
       

masters/templates/masters_home.html
{% extends "index.html" %}
{% load staticfiles %}


{% block styleBlock %}
    <!-- BEGIN GLOBAL MANDATORY STYLES -->

    <link href="{% static 'assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}"
          rel="stylesheet" type="text/css"/>


    </head>
    <!-- END HEAD -->






    <style type="text/css">
        .page-bar {
            margin-bottom: 1px;
        }


    </style>
{% endblock %}



<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 4000);

</script>



{% block content %}


    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{% url 'registration:home' %}">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <span>Masters</span>
            </li>
        </ul>
    </div>



    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert" style="color: black;">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        </div>
    {% endfor %}

    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light ">


        <div class="portlet-body">


            <div class="tiles">

                {% if 'registration.can_view_settings' and 'registration.can_view_nationality' in perms %}
                    <div class="tile bg-red-sunglo" style="height: 170px !important;width: 48% !important;">
                        <a href="{% url 'masters:nationality_masters' %}">
                            <div class="tile-body">
                                <i class="icon-globe"></i>

                            </div>
                            <div class="tile-object">

                                <div class="name">
                                    <h4>Nationality</h4>
                                </div>
                                <!--<div class="number"> 24 Jan 2013 </div>-->
                            </div>
                        </a>
                    </div>
                {% endif %}

                <div class="tile bg-grey-silver" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'masters:nationality_group' %}">
                        <div class="tile-body">
                            <i class="icon-globe"></i>

                        </div>
                        <div class="tile-object">

                            <div class="name">
                                <h4>Nationality Group</h4>
                            </div>
                            <!--<div class="number"> 24 Jan 2013 </div>-->
                        </div>
                    </a>
                </div>

                {% if 'registration.can_view_settings' and 'registration.can_view_religion' in perms %}
                    <div class="tile bg-blue-steel" style="height: 170px !important;width: 48% !important;">
                        <a href="{% url 'masters:religion_masters' %}">
                            <div class="tile-body">
                                <i class="icon-flag"></i>

                            </div>
                            <div class="tile-object">

                                <div class="name">
                                    <h4>Religion</h4>
                                </div>
                                <!--<div class="number"> 24 Jan 2013 </div>-->
                            </div>
                        </a>
                    </div>
                {% endif %}

                {% if 'registration.can_view_settings' and 'registration.can_view_department_master' in perms %}
                    <div class="tile double-down bg-yellow-lemon"
                         style="height: 170px !important;width: 48% !important;">
                        <a href="{% url 'masters:department_master' %}">
                            <div class="tile-body">
                                <i class="icon-briefcase"></i>
                                <!--<img src="../assets/pages/media/profile/photo1.jpg" alt="">-->
                                <!-- <h4>Announcements</h4>
                                 <p> Easily style icon color, size, shadow, and anything that's possible with CSS. </p>-->
                            </div>
                            <div class="tile-object">
                                <div class="name"><h4>Department Master</h4></div>
                                <!--<div class="number"> 24 Jan 2013 </div>-->
                            </div>
                        </a>
                    </div>
                {% endif %}



                <div class="tile bg-blue-hoki" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'masters:house_master_list' %}">
                        <div class="tile-body">
                            <i class="glyphicon glyphicon-list-alt"></i>
                        </div>
                        <div class="tile-object">

                            <div class="name">
                                <h4>House Master</h4>
                            </div>
                        </div>
                    </a>
                </div>


                <div class="tile bg-purple" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'masters:month_masters' %}">
                        <div class="tile-body">
                            <i class="glyphicon glyphicon-list-alt"></i>
                        </div>
                        <div class="tile-object">

                            <div class="name">
                                <h4>Month Master</h4>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="tile bg-green" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'masters:exam_masters' %}">
                        <div class="tile-body">
                            <i class="glyphicon glyphicon-list-alt"></i>
                        </div>
                        <div class="tile-object">

                            <div class="name">
                                <h4>Exam Type</h4>
                            </div>
                            <!--<div class="number"> 24 Jan 2013 </div>-->
                        </div>
                    </a>
                </div>


                <div class="tile bg-yellow" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'masters:tc_type_master' %}">
                        <div class="tile-body">
                            <i class="glyphicon glyphicon-education"></i>
                        </div>
                        <div class="tile-object">

                            <div class="name">
                                <h4>TC Type</h4>
                            </div>
                            <!--<div class="number"> 24 Jan 2013 </div>-->
                        </div>
                    </a>
                </div>

                <div class="tile bg-green-turquoise" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'masters:section_type_master' %}">
                        <div class="tile-body">
                            <i class="fa icon-magnifier-add"></i>
                        </div>
                        <div class="tile-object">

                            <div class="name">
                                <h4>Section Type</h4>
                            </div>
                            <!--<div class="number"> 24 Jan 2013 </div>-->
                        </div>
                    </a>
                </div>

            <div class="tile" style="background-color:#4d9200;height: 170px !important;width: 48% !important;">
                    <a href="{% url 'masters:report_card_term_master' %}">
                        <div class="tile-body">
                            <i class="fa fa-calculator"></i>
                        </div>
                        <div class="tile-object">

                            <div class="name">
                                <h4>Define Report Card Term Names</h4>
                            </div>
                            <!--<div class="number"> 24 Jan 2013 </div>-->
                        </div>
                    </a>
                </div>



                {% if user.is_superuser %}
                    <div class="tile bg-red-sunglo" style="height: 170px !important;width: 48% !important;">
                        <a href="{% url 'masters:template_odoo_config_list' %}">
                            <div class="tile-body">
                                <i class="glyphicon glyphicon-refresh"></i>
                            </div>
                            <div class="tile-object">

                                <div class="name">
                                    <h4>Odoo Server Configuration</h4>
                                </div>
                                <!--<div class="number"> 24 Jan 2013 </div>-->
                            </div>
                        </a>
                    </div>
                {% endif %}


            </div>
        </div>
    </div>



    <!-- END VALIDATION STATES-->


{% endblock %}
                        

masters/templates/template_add_odoo_configuration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>