edsys_assesment/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import registration.urls
import transfer_certificate.urls
import strike_off.urls
import id_generation.urls
import medical.urls
import attendance.urls
import password_reset.urls
import masters.urls
import promotions.urls
import assessment.urls
import parent_portal.urls
import rest_api.urls
from registration import views
import os
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    url(r'^api/', include(rest_api.urls, namespace='api')),
    url(r'^school/', include(registration.urls, namespace='registration')),
    url(r'^$', views.Login, name='login'),
    url(r'^school/', include(transfer_certificate.urls, namespace='transfer_certificate')),
    url(r'^school/', include(strike_off.urls, namespace='strike_off')),
    url(r'^school/', include(id_generation.urls, namespace='id_generation')),
    url(r'^school/', include(medical.urls, namespace='medical')),
    url(r'^school/', include(password_reset.urls, namespace='password_reset')),
    url(r'^school/', include(attendance.urls, namespace='attendance')),
    url(r'^school/', include(masters.urls, namespace='masters')),
    url(r'^school/', include(promotions.urls, namespace='promotions')),
    url(r'^school/', include(assessment.urls, namespace='assessment')),
    url(r'^school/', include(parent_portal.urls, namespace='parent_portal')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('social_django.urls', namespace='social')),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^sso/', include("djssoserver.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ADMIN_URL_ENABLE:
    urlpatterns.append(url(r'^admin/', admin.site.urls))

id_generation/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static, serve


app_name = 'id_generation'

urlpatterns = [
                  url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
                  url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),


    ######################################### ID Details ###################################

                  url(r'^id_menu/$', views.IdMenu, name='id_menu'),
                  url(r'^id_generator/$', views.IdGenerator, name='id_generator'),
                  url(r'^updated_student_template/$', views.UpdatedStudentTemplate, name='updated_student_template'),
                  url(r'^view_student_template/$', views.ViewStudentTemplate, name='view_student_template'),
                  url(r'^view_student_ID_list/$', views.IdGeneratorList, name='view_student_ID_list'),
                  url(r'^id_generate/(?P<std_id>[0-9]+)$', views.IdGenerate, name='id_generate'),
                  url(r'^student_template/$', views.StudentTemplate, name='student_template'),
                  url(r'^student_template_select/$', views.StudentTemplateSelect, name='student_template_select'),
                  url(r'^multiple_student_ID_list/$', views.MultipleStudentIDlist, name='multiple_student_ID_list'),
                  url(r'^print_back/$', views.PrintBack, name='print_back'),
                  url(r'^print_id/(?P<std_id>[0-9]+)$', views.PrintID, name='print_id'),

                  # url(r'^multiple_student_ID_list/$',views.MultipleStudentIDlist, name='multiple_student_ID_list'),
                  url(r'^multiple_ststaff_ID_print/$', views.MultipleStaffIDCard, name='multiple_ststaff_ID_print'),
                  # url(r'^student_template/$',views.StudentTemplate, name='student_template'),

                  url(r'^view_staff_list/$', views.ViewStaffList, name='view_staff_list'),
                  url(r'^staff_template/$', views.StaffTemplate, name='staff_template'),
                  url(r'^staff_id_generate/(?P<usr_id>[0-9]+)$', views.StaffIdGenerate, name='staff_id_generate'),
                  url(r'^print_staff_id/(?P<usr_id>[0-9]+)$', views.PrintStaffID, name='print_staff_id'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masters/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static

app_name = 'masters'

urlpatterns = [

                  ########=================================odoo configuration======================================================
                  url(r'^template_odoo_config_list/$', views.TemplateOdooConfigList, name='template_odoo_config_list'),
                  url(r'^add_odoo_config/$', views.AddOdooConfig, name='add_odoo_config'),
                  url(r'^template_update_config/(?P<config_id>[0-9]+)$', views.TemplateUpdateOdooConfig,
                      name='template_update_config'),
                  url(r'^update_odoo_config/$', views.UpdateOdooConfig, name='update_odoo_config'),
                  url(r'^test_connection/$', views.TestOdooConnection, name='test_connection'),
                  url(r'^start_syncing/$', views.StartOdooSync, name='start_syncing'),
                  url(r'^sync_switch/$', views.OdooSyncOnOff, name='sync_switch'),
                  #=================================================================================================================

                  url(r'^month_masters/$', views.MonthMasters, name='month_masters'),

                  url(r'^masters_home/$', views.ManageMasters, name='masters_home'),
                  url(r'^data_access/$', views.DataAccessMasters, name='data_access'),
                  url(r'^religion_masters/$', views.ManageReligionMasters, name='religion_masters'),
                  url(r'^add_religion_masters/$', views.AddReligionMasters, name='add_religion_masters'),
                  url(r'^update_religion/(?P<religion_id>[0-9]+)$', views.UpdateReligion, name='update_religion'),
                  url(r'^save_updated_religion/$', views.SaveUpdatedReligion, name='save_updated_religion'),
                  url(r'^delete_religion/(?P<religion_id>[0-9]+)$', views.DeleteReligion, name='delete_religion'),

                  # =-==-=-=-=-==-=-=-Nationality Urls=-=-=-====-=-=-=-=

                  url(r'^nationality_masters/$', views.ManageNationalityMasters, name='nationality_masters'),
                  url(r'^add_nationality_masters/$', views.AddNationalityMasters, name='add_nationality_masters'),
                  url(r'^update_nationality/(?P<nationality_id>[0-9]+)$', views.UpdateNationality,
                      name='update_nationality'),
                  url(r'^save_updated_nationality/$', views.SaveUpdatedNationality, name='save_updated_nationality'),
                  url(r'^delete_nationality/(?P<nationality_id>[0-9]+)$', views.DeleteNationality,
                      name='delete_nationality'),

                  # =-=-=-=-=-=-=-=-=-=--Department Master Urls=-=-=-=-=-=-=-=-=-=-
                  url(r'^department_master/$', views.ManageDepartment, name='department_master'),
                  url(r'^add_department_masters/$', views.AddDepartmentMasters, name='add_department_masters'),
                  url(r'^update_department/(?P<department_id>[0-9]+)$', views.UpdateDepartment,
                      name='update_department'),
                  url(r'^save_updated_department/$', views.SaveUpdatedDepartment, name='save_updated_department'),
                  url(r'^delete_department/(?P<department_id>[0-9]+)$', views.DeleteDepartment,
                      name='delete_department'),

                  # =-==-=-=-=-==-=-=-Exam Urls=-=-=-====-=-=-=-=

                  url(r'^exam_masters/$', views.ManageExamMasters, name='exam_masters'),
                  url(r'^add_exam_masters/$', views.AddExamMasters, name='add_exam_masters'),
                  url(r'^update_exam/(?P<exam_type_id>[0-9]+)$', views.UpdateExam,
                      name='update_exam'),
                  url(r'^save_updated_exam/$', views.SaveUpdatedExam, name='save_updated_exam'),
                  url(r'^delete_exam/(?P<exam_type_id>[0-9]+)$', views.DeleteExam,
                      name='delete_exam'),

                  # =-==-=-=-=-==-=-=-Rubrics Urls=-=-=-====-=-=-=-=

                  url(r'^rubrics_masters/$', views.RubricsMasters, name='rubrics_masters'),
                  url(r'^add_rubrics_masters/$', views.AddRubricsMasters, name='add_rubrics_masters'),
                  url(r'^update_rubrics/(?P<rubrics_id>[0-9]+)$', views.UpdateRubrics,
                      name='update_rubrics'),
                  url(r'^save_updated_rubrics/$', views.SaveUpdatedRubrics, name='save_updated_rubrics'),
                  url(r'^delete_rubrics/(?P<rubrics_id>[0-9]+)$', views.DeleteRubrics,
                      name='delete_rubrics'),

                  url(r'^rubrics_category/$', views.RubricsCategory, name='rubrics_category'),
                  url(r'^add_rubrics_category/$', views.AddRubricsCategory, name='add_rubrics_category'),
                  url(r'^update_rubrics_catgory/(?P<rubrics_category_id>[0-9]+)$', views.UpdateRubricsCategory,
                      name='update_rubrics_catgory'),
                  url(r'^save_updated_rubrics_category/$', views.SaveUpdatedRubricsCategory,
                      name='save_updated_rubrics_category'),
                  url(r'^delete_rubrics_category/(?P<rubrics_category_id>[0-9]+)$', views.DeleteRubricsCategory,
                      name='delete_rubrics_category'),

                  url(r'^nationality_group/$', views.NationalityGroup, name='nationality_group'),
                  url(r'^add_nationality_group/$', views.AddNationalityGroup, name='add_nationality_group'),

                  url(r'^update_nationality_group/(?P<nationality_group_id>[0-9]+)$', views.UpdateNationalityGroup,
                      name='update_nationality_group'),
                  url(r'^save_updated_nationality_group/$', views.SaveUpdatedNationalityGroup,
                      name='save_updated_nationality_group'),

                  url(r'^delete_nationality_group/(?P<nationality_group_id>[0-9]+)$', views.DeleteNationalityGroup,
                      name='delete_nationality_group'),

                  # =-==-=-=-=-==-=-=-Home Urls=-=-=-====-=-=-=-=
                  url(r'^house_master_list/$', views.HouseMasterList, name='house_master_list'),
                  url(r'^add_house/$', views.AddHouse, name='add_house'),
                  url(r'^update_hose/(?P<house_id>[0-9]+)$', views.UpdateHose,
                      name='update_hose'),
                  url(r'^save_updated_house/$', views.SaveUpdatedHouse, name='save_updated_house'),
                  url(r'^delete_house/(?P<house_id>[0-9]+)$', views.DeleteHouse,
                      name='delete_house'),

                  url(r'^nationality_group_mapping/$', views.NationalityGroupMapping, name='nationality_group_mapping'),

                  url(r'^group_nationality_mapping/$', views.GroupNationalityMapping, name='group_nationality_mapping'),
                  url(r'^save_group_nationality_mapping/$', views.SaveGroupNationalityMapping,
                      name='save_group_nationality_mapping'),
                  url(r'^delete_group_nationality_mapping/$', views.DeleteGroupNationalityMapping,
                      name='delete_group_nationality_mapping'),

                  url(r'^tc_type_master/$', views.TCTYPEMASTER, name='tc_type_master'),

                  # =-==-=-=-=-==-=-=-Assessment Configration Urls=-=-=-====-=-=-=-=

                  url(r'^assessment_configration/$', views.AssessmentConfigration, name='assessment_configration'),
                  url(r'^add_assessment_configration/$', views.AddAssessmentConfigration,
                      name='add_assessment_configration'),
                  url(r'^update_assessment_configration/(?P<ass_config_id>[0-9]+)$', views.UpdateAssessmentConfigration,
                      name='update_assessment_configration'),

                  url(r'^save_updated_assessment_configraton/$', views.SaveUpdatedAssessmentConfigraton,
                      name='save_updated_assessment_configraton'),
                  url(r'^delete_assessment_configration/(?P<ass_config_id>[0-9]+)$', views.DeleteAssessmentConfigration,
                      name='delete_assessment_configration'),

                  url(r'^assessment_configrtion_roundoff/$', views.AssessmentConfigrtionRoundOff,
                      name='assessment_configrtion_roundoff'),

                  url(r'^assessment_round_off/$', views.AssessmentRoundOff, name='assessment_round_off'),
                  url(r'^add_round_off/$', views.AddRoundOff, name='add_round_off'),
                  # url(r'^round_off_list/$', views.RoundOffList, name='round_off_list'),
                  url(r'^update_round_off/', views.UpdateRoundOff,
                      name='update_round_off'),
                  url(r'^save_updated_round_off/$', views.SaveUpdatedRoundOff, name='save_updated_round_off'),
                  url(r'^delete_round_off/(?P<round_off_id>[0-9]+)$', views.DeleteRoundOff,
                      name='delete_round_off'),
                  url(r'^active_round/$', views.ActiveRound, name='active_round'),
                  url(r'^inactive_round/$', views.InActiveRound, name='inactive_round'),

                  # ============== Section Type ============================

                  url(r'^section_type_master/$', views.SectionTypeMaster, name='section_type_master'),
                  url(r'^add_section_type/$', views.AddSectionType, name='add_section_type'),
                  url(r'^save_section_type/$', views.SaveSectionType, name='save_section_type'),
                  url(r'^update_section_type/(?P<type_id>[0-9]+)$', views.UpdateSectionType,name='update_section_type'),
                  url(r'^save_updated_section_type/$', views.SaveUpdateSectionType, name='save_updated_section_type'),
                  url(r'^delete_section_type/(?P<type_id>[0-9]+)$', views.DeleteSectionType, name='delete_section_type'),

id_generation/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import date,datetime

# Create your models here.

class id_student_selected_template(models.Model):
    template = models.CharField(max_length=25, null=True)
    create_date = models.DateTimeField(default=datetime.now)
    update_date = models.DateTimeField(auto_now=True)

id_generation/templates/id_menu.html
{% extends "index.html" %}
{% load staticfiles %}

{% block styleBlock %}
    <sctipt>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </sctipt>

    <style type="text/css">
        .page-bar {
            margin-bottom: 1px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="page-bar" style="margin-bottom: 1px;">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{% url 'registration:home' %}">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>

            <li>
                <span>ID Cards</span>
            </li>
        </ul>
    </div>


    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert" style="color: black;">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        </div>
    {% endfor %}

    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light ">
        <div class="portlet-body">
            <div class="tiles">
                <div class="tile bg-green-turquoise" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'id_generation:id_generator' %}">
                        <div class="tile-body">
                                <i class="fa fa-id-card" aria-hidden="true"></i>
                        </div>

                        <div class="tile-object">
                            <div class="name text-success"><h4>Student ID Cards </h4></div>
                        </div>
                    </a>
                </div>

                <div class="tile" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'id_generation:view_student_template' %}">
                        <div class="tile-body" style="background-color: #2d6987">
                                <i class="fa fa-id-card" aria-hidden="true"></i>
                        </div>
                        <div class="tile-object">
                            <div class="name text-success"><h4>View/Select Student ID Cards Template</h4></div>
                        </div>
                    </a>
                </div>

                {% comment %}<div class="tile bg-blue" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'id_generation:student_template_select' %}">

                        <div class="tile-body">
                                <i class="fa fa-id-card" aria-hidden="true"></i>
                        </div>
                        <div class="tile-object">
                            <div class="name "><h4  >Student ID Card - Template</h4></div>

                        </div>
                    </a>
                </div>

                <div class="tile double-down bg-purple-studio" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'id_generation:view_staff_list' %}">

                        <div class="tile-body">
                            <i class="fa fa-id-badge " aria-hidden="true"></i>

                        </div>
                        <div class="tile-object">
                            <div class="name "><h4  >Staff ID Cards</h4></div>

                        </div>
                    </a>
                </div>

                <div class="tile bg-blue-hoki" style="height: 170px !important;width: 48% !important;">
                    <a href="{% url 'id_generation:staff_template' %}">

                        <div class="tile-body">
                            <i class="fa fa-id-badge " aria-hidden="true"></i>

                        </div>
                        <div class="tile-object">
                            <div class="name "><h4  >Staff ID Card - Template</h4></div>

                        </div>
                    </a>
                </div>{% endcomment %}

            </div>
        </div>
    </div>
{% endblock %}

id_generation/templates/student_template_select.html
{% extends "index.html" %}
{% load staticfiles %}
{% block ScriptBlock %}

    <Script>
        window.onload = function () {
            //YOUR JQUERY CODE
            $(document).ready(function () {
            });
        }

    </Script>

{% endblock %}

{% block content %}
    <div class="page-bar" style="margin-bottom: 1px;">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{% url 'registration:home' %}">Home</a>
                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="{% url 'id_generation:id_menu' %}">ID Card Menu</a>
                <i class="fa fa-angle-right"></i>
            </li>

            <li>
                <span>Student Template</span>
            </li>
        </ul>
    </div>


    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert" style="color: black;">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        </div>
    {% endfor %}



    <!-- BEGIN VALIDATION STATES-->
    <div class="portlet light portlet-fit portlet-form ">
        <div class="portlet-title">
            <div class="caption">
                <i class="icon-settings font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Student Template</span>
            </div>

        </div>
        <div class="portlet-body">


            <!-- BEGIN FORM-->
            <form action="{% url 'id_generation:student_template' %}"  class="form-horizontal" method="POST"
                  enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-body">
                    <div class="row">
                        <div class="" style="margin-left: 35%">
                            <label class="col-md-2 control-label" style="margin-top: -0px"> Select:</label>
                            <div class="col-md-4">
                                <input type="radio" name="select" value="own" required> Own
                                <input type="radio" name="select" value="school"> School
                                <button  style="margin-left: 15%" type="submit" id="save1" class="btn green">Download</button>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
               {% comment %} <div class="form-actions">
                    <div class="row">
                        <div class="" style="margin-left: 35%">
                            <button type="submit" id="save1" class="btn green">Download</button>
                            <a href="{% url 'masters:exam_masters' %}">
                                <button type="button" class="btn grey-salsa btn-outline">Cancel</button>
                            </a>
                        </div>
                    </div>
                </div>{% endcomment %}
            </form>
            <!-- END FORM-->
        </div>
    </div>
{% endblock %}

<!-- BEGIN CORE PLUGINS -->

id_generation/templates/view_staff_list.html
{% extends "index.html" %}
{% load staticfiles %}


{% block styleBlock %}
    <!-- BEGIN GLOBAL MANDATORY STYLES -->

    <link href="{% static 'assets/global/plugins/datatables/datatables.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css' %}"
          rel="stylesheet" type="text/css"/>


    </head>
    <!-- END HEAD -->

{% endblock %}
{% block ScriptBlock %}
    <script>

        window.onload = function () {

            var select_all = document.getElementById("select_all"); //select all checkbox
            var checkboxes = document.getElementsByClassName("checkbox"); //checkbox items

            //select all checkboxes
            select_all.addEventListener("change", function (e) {
                for (i = 0; i < checkboxes.length; i++) {
                    checkboxes[i].checked = select_all.checked;
                }
            });

            for (var i = 0; i < checkboxes.length; i++) {
                checkboxes[i].addEventListener('change', function (e) { //".checkbox" change
                    //uncheck "select all", if one of the listed checkbox item is unchecked
                    if (this.checked == false) {
                        select_all.checked = false;
                    }
                    //check "select all" if all checkbox items are checked
                    if (document.querySelectorAll('.checkbox:checked').length == checkboxes.length) {
                        select_all.checked = true;
                    }
                });
            }

            var favorite = [];
            $("#generate").click(function () {
                var checked = $('#sample_1').find(':checked').length;
                if (!checked)
                    alert('Please select atleast one record to generate ID!');
                else {
                    $.each($("input[name='check']:checked"), function () {

                        favorite.push($(this).val());
                    });
                    strID = favorite.join(", ")
                    console.log("favoritefavorite", favorite.join(", "))

                    $("#strikeId").val(strID);
                    $('#myModal').modal('toggle');
                    $('#myModal').modal('show');
                }
            });

            $(document).ready(function () {
                $('#generate').attr('disabled', true);
                $('#select_all').attr('disabled', true);

                var forms = $('.abc')
                if(forms.length > 0)
                 {
                        $('#generate').attr('disabled', false);
                        $('#select_all').attr('disabled', false);
                 }

                $('#submit2').click(function () {
                    $('#formfield1').submit();
                });
            });


             $('#sample_1').dataTable().fnDestroy();

            $('#sample_1').dataTable({
                "aoColumnDefs": [
                    {'bSortable': false}
                ]
            });
        }


        window.setTimeout(function () {
            $(".alert").fadeTo(500, 0).slideUp(500, function () {
                $(this).remove();
            });
        }, 4000);

    </script>

{% endblock %}

{% block content %}
    <div class="page-bar" style="margin-bottom: 1px;">
        <ul class="page-breadcrumb">
            <li>
                <i class="icon-home"></i>
                <a href="{% url 'registration:home' %}">Home</a>

                <i class="fa fa-angle-right"></i>
            </li>
            <li>
                <a href="{% url 'id_generation:id_menu' %}">ID Card Menu</a>
                <i class="fa fa-angle-right"></i>
            </li>


            <li>
                <span>Staff List</span>
            </li>

        </ul>

    </div>


    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert" style="color: black;">{{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        </div>
    {% endfor %}
    <!-- BEGIN VALIDATION STATES-->

    <div class="portlet light">
        <div class="portlet-title">
            <div class="caption font-dark">
                <i class="icon-settings font-red"></i>
                <span class="caption-subject font-red sbold uppercase">Manage User Profile</span>
            </div>

        </div>
        <div class="portlet-body">

        <form  method = "post" action="{% url 'id_generation:multiple_ststaff_ID_print' %}"  id = "formfield1">
            {% csrf_token %}
            <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                <thead>
                <tr>
                    <th style="display:none;" class="sorting" tabindex="0" aria-controls="sample_1" rowspan="1"
                        colspan="1" aria-sort="ascending" aria-label=" Serialno : activate to sort column ascending"
                        style="width: 145px;">Serial No
                    </th>
                    <th> <input type="checkbox" id="select_all" />Select All </th>
                    <th class="sorting"> First Name</th>
                    <th> Middle Name</th>
                    <th> Last Name</th>
                    <th> Role</th>
                    <th> Email</th>
                    <th> Contact</th>
                    <th>Generate ID</th>

                </tr>
                </thead>
                <tbody>
                {% for staff in staff_list %}
                    <tr class="abc">

                    <td style="display:none">{{ staff.id }}</td>
                    <td><input class="checkbox" type='checkbox'  name='check' value="{{ staff.id}}" ></td>
                    <td>{{ staff.first_name }}</td>
                    <td>
                        {% if staff.middle_name %}{{ staff.middle_name }} {% else %} {{ '' }} {% endif %}
                    </td>
                    <td> {{ staff.last_name }} </td>
                    <td> {{ staff.role.name }} </td>
                    <td> {{ staff.email }} </td>

                    <td> {{ staff.staff_relation.all.0.contact_num }} </td>
                    <td><a class="btn blue btn-block" href="{% url 'id_generation:staff_id_generate' staff.id %}">Generate ID Card</a></td>
{#                    {% url 'id_generation:id_generate' obj.id %}#}

                {% endfor %}
                </tr>
                </tbody>
            </table>

            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-lg-12 text-center">
                        <button type="button" value="Submit" id="generate" class="btn blue btn btn-primary" style="cursor: pointer; width:200px;" >Generate -ID Card </button>
                    </div>
                </div>
            </div>
        </form>
        </div>
    </div>
    <!-- END VALIDATION STATES-->
<div class="modal fade" id="myModal" role="dialog">
								    <div class="modal-dialog modal-sm">
								      <div class="modal-content">
								      <form  method="post"  action="{% url 'id_generation:multiple_ststaff_ID_print' %}" id="formfield2">
		             						{% csrf_token %}

								           <div class="modal-header">
								           		<input type="hidden" name="strikeId" id = "strikeId">
								                   <button type="button" class="close" data-dismiss="modal"></button>

								          <h4 class="modal-title">Are your sure want to generate ID for selected staff..?</h4>

								          <button type="button" value="Submit2" id="submit2" class="btn btn-default" data-dismiss="modal">Yes </button>
								          <button type="button" class="btn btn-default" data-dismiss="modal">No</button>


								          </div>
								        </form>
								      </div>
								    </div>
								 </div>

{% endblock %}